// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvr3QoGq4RQkPX5NaYNuL9jurE_bdDF4g',
    appId: '1:1034224141733:ios:d04908f049d31df74e944c',
    messagingSenderId: '1034224141733',
    projectId: 'trackingappmini',
    databaseURL: 'https://trackingappmini-default-rtdb.firebaseio.com',
    storageBucket: 'trackingappmini.appspot.com',
    iosBundleId: 'com.example.loginFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHFDCt6wazbEvyS8oPsLePdAMYGpMrXBM',
    appId: '1:1034224141733:web:c6f7c81036ed48104e944c',
    messagingSenderId: '1034224141733',
    projectId: 'trackingappmini',
    authDomain: 'trackingappmini.firebaseapp.com',
    databaseURL: 'https://trackingappmini-default-rtdb.firebaseio.com',
    storageBucket: 'trackingappmini.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHFDCt6wazbEvyS8oPsLePdAMYGpMrXBM',
    appId: '1:1034224141733:web:c6f7c81036ed48104e944c',
    messagingSenderId: '1034224141733',
    projectId: 'trackingappmini',
    authDomain: 'trackingappmini.firebaseapp.com',
    databaseURL: 'https://trackingappmini-default-rtdb.firebaseio.com',
    storageBucket: 'trackingappmini.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvr3QoGq4RQkPX5NaYNuL9jurE_bdDF4g',
    appId: '1:1034224141733:ios:d04908f049d31df74e944c',
    messagingSenderId: '1034224141733',
    projectId: 'trackingappmini',
    databaseURL: 'https://trackingappmini-default-rtdb.firebaseio.com',
    storageBucket: 'trackingappmini.appspot.com',
    iosBundleId: 'com.example.loginFirebase',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOqzHDmMEDwqaQRN20uw79PRrS0hLWSUE',
    appId: '1:1034224141733:android:98637887588b5a3b4e944c',
    messagingSenderId: '1034224141733',
    projectId: 'trackingappmini',
    databaseURL: 'https://trackingappmini-default-rtdb.firebaseio.com',
    storageBucket: 'trackingappmini.appspot.com',
  );

}